name: cicd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: cicd-group-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci-smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba # v6
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version-file: "pyproject.toml"

      - name: install dependencies
        run: uv sync --all-extras --dev

      - name: smoke test
        run: make ci-smoke-test
