name: commit-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commit-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@a02a550bdd3185dba2ebb6aa98d77047ce54ad21 # v6
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version-file: "pyproject.toml"

      - name: install dependencies
        run: uv sync --all-extras --dev

      - name: commit check
        run: uv run cz check --rev-range HEAD~1..HEAD
