name: pr-title-lint

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  pr-title-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ytanikin/pr-conventional-commits@6ac1cea04190fc076b0e539025501d7e7d241ac1 # 1.4.0
        with:
          task_types: '["build","chore","ci","docs","feat","fix","perf","refactor","revert", "style", "test"]'
          add_label: "false"
